### ISSUE TITLE
Error after build

### ISSUE THREAD

**Issue by Designer023** [fractaldimensions/sanity-plugin-visual-options#21]
Hi 

I'm experiencing an issue after build when serving a Santy site. This happens on local and when deployed.

Using `sanity-plugin-visual-options@2.0.1` and `sanity@3.19.2`

```
Uncaught error: xe.default.div is not a function
https://SITENAME/static/sanity-250ce451.js:8538:21119
TypeError: xe.default.div is not a function
    at https://SITENAME/static/sanity-250ce451.js:8538:21119
    at https://SITENAME/static/sanity-250ce451.js:11291:54416
```

Is this something that you have seen before? I'm struggling to debug it because it only happen once built, so it's minified code 😢 

Any help would be greatly appreciated

Thanks

**Comment by nicktaylor** [comment]
Hey @Designer023, this isn't something I've seen before unfortunately. Is this running on Node or Bun? Could you also provide the version number in case it's related? Thanks!
