### ISSUE TITLE
Accept Any Image

### ISSUE THREAD

**Issue by fddigital-uk** [fractaldimensions/sanity-plugin-visual-options#3]
Currently the project only accepts React components, and has only been tested with SVGs being returned. Consider allowing use of standard images such as PNGs and JPGs.

**Comment by nicktaylor** [comment]
Closing as this can be achieved by setting the icon in the following way:
```js
{
  ...,
  icon: () => <img src="/path/to/image.png" />
}
```

`import React from 'react'` will be required within the schema file for this to work.
