### ISSUE TITLE
The plugin is not installable with the latest version of Sanity studio v2.34.0.

### ISSUE THREAD

**Issue by danielskogstad** [fractaldimensions/sanity-plugin-visual-options#7]
I have suggested a dependency update here: https://github.com/danielskogstad/sanity-plugin-visual-options/tree/patch-1

The plugin looks to work fine with these changes in our installation, seems there is only an issue due to dependency versions mismatching with the newest Sanity studio version.

**Comment by nicktaylor** [comment]
Thanks for reporting, I'll set aside some time to get this updated and published this week.

There are also a couple of additional updates/features that I've been meaning to publish, so that'll go with it.

**Comment by nicktaylor** [comment]
@danielskogstad This has now been updated, it appears to be working via `sanity install` for me on version 2.34. Please try and let me know if you are still experiencing issues, cheers!

**Comment by nicktaylor** [comment]
Assumed working now, working on multiple 2.34.x projects for me. Closing.
